apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 20d
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          resources:
            requests:
              storage: 60Gi
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          resources:
            requests:
              storage: 20Gi
