apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-pruner
  namespace: pipelines-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-pruner
rules:
  - apiGroups:
      - 'tekton.dev'
    resources:
      - pipelines
      - pipelineresources
      - pipelineruns
      - tasks
      - taskruns
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - secrets
    verbs:
      - get
      - list
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-pruner
subjects:
  - kind: ServiceAccount
    name: cloud-pruner
    namespace: pipelines-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-pruner
