apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hive-resource-update-role
  namespace: hive
rules:
  - apiGroups:
      - 'hive.openshift.io'
    resources:
      - clusterimagesets
      - clusterpools
      - clusterdeployments
      - clusterdeploymentcustomizations
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - 'hive.openshift.io'
    resources:
      - clusterclaims
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create 
      - get
      - list
      - patch
      - watch
  - apiGroups: 
      - 'project.openshift.io'
    resources:
      - projects
    verbs: 
      - get
      - list
      - watch
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hive-resource-update-role
  namespace: hive
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: pipelines-ci
  - kind: ServiceAccount
    name: pipeline
    namespace: anataraj
  - kind: ServiceAccount
    name: pipeline
    namespace: bgirriam
  - kind: ServiceAccount
    name: pipeline
    namespace: diagrawa
  - kind: ServiceAccount
    name: pipeline
    namespace: jgarg
  - kind: ServiceAccount
    name: pipeline
    namespace: kabhishe-tests
  - kind: ServiceAccount
    name: pipeline
    namespace: ldaruri
  - kind: ServiceAccount
    name: pipeline
    namespace: mbison
  - kind: ServiceAccount
    name: pipeline
    namespace: nisagarw
  - kind: ServiceAccount
    name: pipeline
    namespace: ppitonak
  - kind: ServiceAccount
    name: pipeline
    namespace: ppunamiy
  - kind: ServiceAccount
    name: pipeline
    namespace: priyjain
  - kind: ServiceAccount
    name: pipeline
    namespace: rashmi-acctest
  - kind: ServiceAccount
    name: pipeline
    namespace: rbehera
  - kind: ServiceAccount
    name: pipeline
    namespace: sashture
  - kind: ServiceAccount
    name: pipeline
    namespace: sselvan
  - kind: ServiceAccount
    name: pipeline
    namespace: vaaynure
  - kind: ServiceAccount
    name: pipeline
    namespace: vdemeest
  - kind: ServiceAccount
    name: pipeline
    namespace: smanthin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hive-resource-update-role
