apiVersion: v1
kind: Secret
metadata:
  name: pac-github-token
type: Opaque
stringData:
  pac-github-token: "$PAC_GITHUB_TOKEN"
  pac-github-org: "$PAC_GITHUB_ORG"
  pac-github-webhook-token: "$PAC_GITHUB_WEBHOOK_TOKEN"
