apiVersion: v1
kind: Secret
metadata:
  name: pac-gitlab
type: Opaque
stringData:
  gitlab-token: "$GITLAB_TOKEN"
  gitlab-group-ns: "$GITLAB_GROUP_NAMESPACE"
  gitlab-project-id: "$GITLAB_PROJECT_ID"
  gitlab-webhook-token: "$GITLAB_WEBHOOK_TOKEN"
