apiVersion: v1
kind: Secret
metadata:
  name: quay-io-dockerconfig
  namespace: pipelines-ci
stringData:
  config.json: |
    {
      "auths": {
        "quay.io": {
          "auth": "$QUAY_AUTH",
          "email": ""
        }
      }
    }